name: AsureMarriages
version: '1.0'
author: SaintQd
main: org.saintqd.asuremarriages.AsureMarriages
description: AsureMarriages Plugin
api-version: '26.2'
dependencies:
  server:
    AsureLib:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Vault:
      load: BEFORE
      required: false
permissions:
  asuremarriages.admin:
    description: Access to admin commands.
    default: op
  asuremarriages.offer:
    description: Возможность совершать предложения брака.
    default: op
  asuremarriages.divorce:
    description: Возможность расторгать брак.
    default: true
  asuremarriages.ender:
    description: Возможность открывать эндер-сундук партнёра.
    default: op
  asuremarriages.tp:
    description: Возможность телепортироваться к партнёру.
    default: op
  asuremarriages.kiss:
    description: Возможность телепортироваться к партнёру.
    default: true
  asuremarriages.woohoo:
    description: Возможность уединяться с партнёром.
    default: true