name: AsureMarriages
version: '1.0'
author: SaintQd
main: org.saintqd.asuremarriages.AsureMarriages
api-version: '26.2'
depend: [AsureLib]
softdepend: [PlaceholderAPI,Vault]
permissions:
  asuremarriages.admin:
    description: Access to admin commands.
    default: op